from enum import Enum

class Source(Enum):
    Obsolete = 'Obsolete'
    LEVER = 'Lever'
    GREENHOUSE = 'Greenhouse'
    RECRUITEE = 'Recruitee'
    WORKABLE = 'Workable'
    WORKDAY = 'Workday'
    ICIMS = 'iCIMS'
    WEBSITE = 'Website'
    SMART_RECRUITERS = 'SmartRecruiters'
    SUCCESS_FACTORS = 'SuccessFactors'
    TALEO = 'Taleo'
    CSOD = 'Cornerstone OnDemand'
    TRAKSTAR = 'Trakstar Hire'
    APPLICANT_PRO = "ApplicantPro"
    ISOLVED = 'iSolved Hire'
    APPLICANT_POOL = "ApplicantPool"
    APPLICANT_LIST = 'ApplicantList'
    AAIM_TRACK = 'AAIMTrack'
    PREVUE_APS = 'Prevue APS'
    PAYCOR = "Paycor"
    HCAREERS = "Hcareers"
    PINPOINT = "Pinpoint"
    ASHBY = "Ashby"
    TEAMWORK_ONLINE = "Teamwork Online"
    EDDY = "Eddy"
    HOSPITAL_CAREERS = "HospitalCareers"
    HIRING_THING = "HiringThing"
    TALENT_NEST = "TalentNest"
    FRESH_TEAM = "FreshTeam"
    ORACLE_CLOUD = 'Oracle Cloud HCM'
    PHENOM_PEOPLE = 'Phenom People'
    CAREER_PLUG = 'CareerPlug'
    ULTIPRO = 'Ultipro'
    VIVAHR = 'Vivahr'
    APPLI_TRACK = 'AppliTrack'
    DAYFORCE = 'Dayforce HCM'
    GET_HIRED = "GetHired"
    GO_HIRE = "GoHire"
    ZOHO_RECRUIT = "Zoho Recruit"
    PRISM = "PrismHR"
    SILK_ROAD = "SilkRoad"
    PAGEUP = "Pageup"
    JOBVITE = 'Jobvite'
    TED_K12 = 'TedK12'
    APPLY_TO_JOB = 'ApplyToJob'
    PAYCOM = "Paycom"
    PAYLOCITY = 'Paylocity'
    HRM_DIRECT = 'HRMDirect'
    APPLOI = "Apploi"
    HIREOLOGY = "Hireology"
    BAMBOO_HR = "BambooHR"
    APPLICANT_STACK = "ApplicantStack"
    HIRE_CLICK = "HireClick"
    HIRE_BRIDGE = "HireBridge"
    VOLUNTEER_MATCH = "VolunteerMatch"
    BRASS_RING = "BrassRing"
    CATS_ONE = "CatsOne"
    SAASHR = "Saashr"
    APS_CAREER_PORTAL = "APS Career Portal"
    CAREER_PAGE = "CareerPage"
    BREEZY = "Breezy"
    OUR_CAREER_PAGES = 'Our Career Pages'
    EIGHTFOLD = 'Eightfold'
    RECRUITERFLOW = "Recruiterflow"
    PEOPLEA_DMIN = "PeopleAdmin"
    TTC_PORTALS = "TTC Portals"
    BULLHORN = "Bullhorn"
    POWER_SCHOOL = "PowerSchool"
    ADP = "ADP"
    RIPPLING = "Rippling"
    JIBE = "Jibe Talent"
    ATS_ON_DEMAND = "ATS OnDemand"
    JOB_SCORE = "JobScore"
    JOBSOID = "Jobsoid"
